/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkI5TGNEYmxhVmdDVTg1dWdJY3JhMG44QlNBNkNOUzlZY0t6bW9QYXJGND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSm9NTEFQZUhZSmhEN3JoZHF6WEF4eWZ6K3Z2alJlN1BuTFd4NUFIM0UzOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPQzZZcWpCTE1DSTZ0cDdURWFiUlM1Uk51SE14MEdFejNDQ1pFcm5DK0drPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2Yld3azJPdnhtMGdXWUpEeDVaRkpneiszN3Q1RHVDQUdVcVZNOXl2U0N3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVObXBEUHlZRWozOThvWkhlZzIrdHppTkFQUnNLcXJXRDZBUDNuOGhBM2M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFwMFJRL1UrKzdIUXA2R29RKzZnQStVb0FDUVJhMVVuWkQvL0x2N3JhMlU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0xYY0RvZGJWTUQ4WXJxWHk0Y04xTUozYjFxVTFWNzZIY2Q4Y2V2L20waz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWFQveGpuMElpTExwVXVmbE9qOFVReTM2dDkra0Jqd21jQ1VXQ25YZHNFMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1oU2dMUHZMdHRiTERyaWx6SWV4bnNVNDdCNHZ2ZzVRb3NLekQ5N09LMzJLZFdzMlh5b1NwT2d5ZHRWKzZ4aHlaU3dWem45eXpFUGcxbnkzU0lNdkJ3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIyLCJhZHZTZWNyZXRLZXkiOiI1eUh1R0VjN3BpV3luOVdRNzhvc0g5TU1naVEvVWZnMGdIU24vTWFLUHNzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NTYyMDMzMDU5MkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJFNDI1MjY5QTdFRjQzRTk0NzhGOTY5QTRENjZBRjM3RiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMzMjE3NDY0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTU2MjAzMzA1OTJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODNBRjVEMjEyMDQzMDI2RkUzRkI5RTFCMUMxMzg2RTYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMzIxNzQ2NH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiLTRxSC1Kc0xRTzYxYXMwVWIzYVM3ZyIsInBob25lSWQiOiI0YTA0M2E5Mi04ZjViLTRhOTMtOTNiMy03OWZkMjU1ZTA2YzEiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTWdBREc4OWRrWkpMZGFodWQ0NHpSNDJZRGlBPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVSQnhhT1FqbjNQS2JIeDZxMFFuSE5COFFwQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJNTVk5TVhBOCIsIm1lIjp7ImlkIjoiMjU1NjIwMzMwNTkyOjUyQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Iu+8ou+8rO+8oe+8o++8q++8qe+8pSDvvLrvvKXvvLLvvK8g77yZ8J+PgPCfjq7wn6SP8J+Pv/CfmI4ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0lINTk3RURFSktadTdvR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlYyRGtEczduZ3NUZ3BDYVAyRU5rejlKNW5PQVBhS21JUjFidGgreDJhRXM9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImdFcndPZTdCNDRXVDRlZ1hyb3NNT3hEakN3THp3b3JlTEJiVlpocnpoQVB3b0xHNENiQXBRdXF4eVZ1cUppM2E3WmR4MmNiazhTUkNhUXdyRHZVYkNBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiI1eXVRLzFwdTNNTVRhKzZlV2s3QVlKeExPdjcxK1l2amltcUo4TStHN1RETi84cGVpWXJRenMrbEVSQVBFdjFPalZwU2tpNy9zaTdZWXNWY0Rja0dBdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NTYyMDMzMDU5Mjo1MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWZGc1QTdPNTRMRTRLUW1qOWhEWk0vU2VaemdEMmlwaUVkVzdZZnNkbWhMIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMzMjE3NDQwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU9qbyJ9'
const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "255";
const author = process.env.STICKER_AUTHOR || 'blackiezero9';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '255620330592';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'MWEUSI MD GAMER';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
